name: Docker Image on Release

on:
  release:
    types: [published]

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        run: |
          docker build -t ghcr.io/eulentier161/dockerbase -t ghcr.io/eulentier161/dockerbase:${VERSION} .
          docker push -a ghcr.io/eulentier161/dockerbase
